const express = require('express');
const app = express();
app.use(express.json());

function registerRoutes(routes) {
  routes.forEach(r => {
    const method = r.method.toLowerCase();
    if (typeof app[method] === 'function') {
      app[method](r.path, (req, res) => {
        res.json({ endpoint: r.path, message: 'Not implemented', received: req.body });
      });
    }
  });
}

const geminiRoutes = [
  { method: 'POST', path: '/api/v1/gemini/generate-bio' },
  { method: 'POST', path: '/api/v1/gemini/generate-sales-email' },
  { method: 'POST', path: '/api/v1/gemini/generate-objection-responses' },
  { method: 'POST', path: '/api/v1/gemini/auto-summary-profile' },
  { method: 'POST', path: '/api/v1/gemini/linkedin-post' },
  { method: 'POST', path: '/api/v1/gemini/generate-product-pitch' },
  { method: 'POST', path: '/api/v1/gemini/faq-answer' },
  { method: 'POST', path: '/api/v1/gemini/ai-script-call' },
  { method: 'POST', path: '/api/v1/gemini/meeting-recap' },
  { method: 'POST', path: '/api/v1/gemini/auto-detect-lead-stage' },
  { method: 'POST', path: '/api/v1/gemini/next-step' },
  { method: 'POST', path: '/api/v1/gemini/spin-questions' },
  { method: 'POST', path: '/api/v1/gemini/mini-guide' },
  { method: 'POST', path: '/api/v1/gemini/sentiment-analysis' },
  { method: 'POST', path: '/api/v1/gemini/suggest-title' },
  { method: 'POST', path: '/api/v1/gemini/agenda-suggestion' },
  { method: 'POST', path: '/api/v1/gemini/auto-reply-chat' },
  { method: 'POST', path: '/api/v1/gemini/generate-slogan' },
  { method: 'POST', path: '/api/v1/gemini/summarize-article' },
  { method: 'POST', path: '/api/v1/gemini/review-copy' },
  { method: 'POST', path: '/api/v1/gemini/generate-cta' },
  { method: 'POST', path: '/api/v1/gemini/thank-you-note' },
  { method: 'POST', path: '/api/v1/gemini/suggest-product-name' },
  { method: 'POST', path: '/api/v1/gemini/whatsapp-message' },
  { method: 'POST', path: '/api/v1/gemini/followup-message' },
  { method: 'POST', path: '/api/v1/gemini/list-faq' },
  { method: 'POST', path: '/api/v1/gemini/tech-answer' },
  { method: 'POST', path: '/api/v1/gemini/generate-checklist' },
  { method: 'POST', path: '/api/v1/gemini/roleplay' },
  { method: 'POST', path: '/api/v1/gemini/generate-goals' },
  { method: 'POST', path: '/api/v1/gemini/email-subject' },
  { method: 'POST', path: '/api/v1/gemini/video-script' },
  { method: 'POST', path: '/api/v1/gemini/client-questions' },
  { method: 'POST', path: '/api/v1/gemini/welcome-message' },
  { method: 'POST', path: '/api/v1/gemini/motivation' },
  { method: 'POST', path: '/api/v1/gemini/special-offer' },
  { method: 'POST', path: '/api/v1/gemini/negotiation-argument' },
  { method: 'POST', path: '/api/v1/gemini/competitor-analysis' },
  { method: 'POST', path: '/api/v1/gemini/webinar-topic' },
  { method: 'POST', path: '/api/v1/gemini/write-case' },
  { method: 'POST', path: '/api/v1/gemini/simulate-client-question' },
  { method: 'POST', path: '/api/v1/gemini/simplify-text' },
  { method: 'POST', path: '/api/v1/gemini/daily-task' },
  { method: 'POST', path: '/api/v1/gemini/generate-quiz' },
  { method: 'POST', path: '/api/v1/gemini/review-script' },
  { method: 'POST', path: '/api/v1/gemini/banner-text' },
  { method: 'POST', path: '/api/v1/gemini/campaign-name' },
  { method: 'POST', path: '/api/v1/gemini/hashtags' },
  { method: 'POST', path: '/api/v1/gemini/auto-email-reply' },
  { method: 'POST', path: '/api/v1/gemini/text-diagnosis' }
];

const openaiRoutes = [
  { method: 'POST', path: '/api/v1/openai/classify-link' },
  { method: 'POST', path: '/api/v1/openai/suggest-link-title' },
  { method: 'POST', path: '/api/v1/openai/optimize-bio-seo' },
  { method: 'POST', path: '/api/v1/openai/translate-bio' },
  { method: 'POST', path: '/api/v1/openai/auto-keywords' },
  { method: 'POST', path: '/api/v1/openai/classify-intent' },
  { method: 'POST', path: '/api/v1/openai/summarize' },
  { method: 'POST', path: '/api/v1/openai/email-analyze' },
  { method: 'POST', path: '/api/v1/openai/auto-reply' },
  { method: 'POST', path: '/api/v1/openai/blog-content' },
  { method: 'POST', path: '/api/v1/openai/brainstorm' },
  { method: 'POST', path: '/api/v1/openai/cta-suggestion' },
  { method: 'POST', path: '/api/v1/openai/linkedin-optimizer' },
  { method: 'POST', path: '/api/v1/openai/followup-email' },
  { method: 'POST', path: '/api/v1/openai/call-questions' },
  { method: 'POST', path: '/api/v1/openai/competitor-compare' },
  { method: 'POST', path: '/api/v1/openai/sentiment' },
  { method: 'POST', path: '/api/v1/openai/generate-faq' },
  { method: 'POST', path: '/api/v1/openai/optimize-copy' },
  { method: 'POST', path: '/api/v1/openai/email-title' },
  { method: 'POST', path: '/api/v1/openai/features-roadmap' },
  { method: 'POST', path: '/api/v1/openai/simulate-customer-question' },
  { method: 'POST', path: '/api/v1/openai/quick-chat-reply' },
  { method: 'POST', path: '/api/v1/openai/project-namer' },
  { method: 'POST', path: '/api/v1/openai/banner-text' },
  { method: 'POST', path: '/api/v1/openai/text-diagnosis' },
  { method: 'POST', path: '/api/v1/openai/whatsapp-rewrite' },
  { method: 'POST', path: '/api/v1/openai/training-quiz' },
  { method: 'POST', path: '/api/v1/openai/sales-argument' },
  { method: 'POST', path: '/api/v1/openai/team-feedback' },
  { method: 'POST', path: '/api/v1/openai/product-description' },
  { method: 'POST', path: '/api/v1/openai/quick-guide' },
  { method: 'POST', path: '/api/v1/openai/suggest-links' },
  { method: 'POST', path: '/api/v1/openai/engagement-analysis' },
  { method: 'POST', path: '/api/v1/openai/slogan-generator' },
  { method: 'POST', path: '/api/v1/openai/operational-checklist' },
  { method: 'POST', path: '/api/v1/openai/special-offer' },
  { method: 'POST', path: '/api/v1/openai/tech-answer-opt' },
  { method: 'POST', path: '/api/v1/openai/negotiation-argument' },
  { method: 'POST', path: '/api/v1/openai/commercial-proposal' },
  { method: 'POST', path: '/api/v1/openai/meeting-date' },
  { method: 'POST', path: '/api/v1/openai/instagram-optimizer' },
  { method: 'POST', path: '/api/v1/openai/report-summary' },
  { method: 'POST', path: '/api/v1/openai/profile-diagnosis' },
  { method: 'POST', path: '/api/v1/openai/onboarding-message' },
  { method: 'POST', path: '/api/v1/openai/suggest-hashtags' },
  { method: 'POST', path: '/api/v1/openai/thank-you-note' },
  { method: 'POST', path: '/api/v1/openai/tech-copy-rewrite' },
  { method: 'POST', path: '/api/v1/openai/proposal-template' },
  { method: 'POST', path: '/api/v1/openai/skill-analysis' }
];

const slackRoutes = [
  { method: 'POST', path: '/api/v1/slack/notify-new-user' },
  { method: 'POST', path: '/api/v1/slack/notify-goal-achieved' },
  { method: 'POST', path: '/api/v1/slack/alert-inactive-profile' },
  { method: 'POST', path: '/api/v1/slack/send-daily-summary' },
  { method: 'POST', path: '/api/v1/slack/feedback-received' },
  { method: 'POST', path: '/api/v1/slack/notify-new-lead' },
  { method: 'POST', path: '/api/v1/slack/notify-bug' },
  { method: 'POST', path: '/api/v1/slack/meeting-scheduled' },
  { method: 'POST', path: '/api/v1/slack/welcome-message' },
  { method: 'POST', path: '/api/v1/slack/send-motivation' },
  { method: 'POST', path: '/api/v1/slack/alert-integration-failure' },
  { method: 'POST', path: '/api/v1/slack/task-assigned' },
  { method: 'POST', path: '/api/v1/slack/send-nps' },
  { method: 'POST', path: '/api/v1/slack/alert-sla-breach' },
  { method: 'POST', path: '/api/v1/slack/pipeline-update' },
  { method: 'POST', path: '/api/v1/slack/reminder-followup' },
  { method: 'POST', path: '/api/v1/slack/notify-proposal-approved' },
  { method: 'POST', path: '/api/v1/slack/notify-comment' },
  { method: 'POST', path: '/api/v1/slack/alert-churn' },
  { method: 'POST', path: '/api/v1/slack/birthday-congrats' },
  { method: 'POST', path: '/api/v1/slack/share-training' },
  { method: 'POST', path: '/api/v1/slack/good-week-message' },
  { method: 'POST', path: '/api/v1/slack/deploy-failure' },
  { method: 'POST', path: '/api/v1/slack/vacation-approved' },
  { method: 'POST', path: '/api/v1/slack/remind-meeting' },
  { method: 'POST', path: '/api/v1/slack/new-file' },
  { method: 'POST', path: '/api/v1/slack/project-risk' },
  { method: 'POST', path: '/api/v1/slack/deal-closed' },
  { method: 'POST', path: '/api/v1/slack/policy-update' },
  { method: 'POST', path: '/api/v1/slack/weekly-insights' },
  { method: 'POST', path: '/api/v1/slack/auto-away' },
  { method: 'POST', path: '/api/v1/slack/integration-issue' },
  { method: 'POST', path: '/api/v1/slack/crm-update-reminder' },
  { method: 'POST', path: '/api/v1/slack/alert-important-lead' },
  { method: 'POST', path: '/api/v1/slack/welcome-new-hire' },
  { method: 'POST', path: '/api/v1/slack/payment-failure' },
  { method: 'POST', path: '/api/v1/slack/monthly-results' },
  { method: 'POST', path: '/api/v1/slack/product-update-reminder' },
  { method: 'POST', path: '/api/v1/slack/auto-closing-message' },
  { method: 'POST', path: '/api/v1/slack/training-scheduled' },
  { method: 'POST', path: '/api/v1/slack/change-owner' },
  { method: 'POST', path: '/api/v1/slack/poll-notification' },
  { method: 'POST', path: '/api/v1/slack/doc-sign-reminder' },
  { method: 'POST', path: '/api/v1/slack/reactivated-lead' },
  { method: 'POST', path: '/api/v1/slack/partnership-message' },
  { method: 'POST', path: '/api/v1/slack/sla-update' },
  { method: 'POST', path: '/api/v1/slack/new-leads-arrival' },
  { method: 'POST', path: '/api/v1/slack/share-productivity-tip' },
  { method: 'POST', path: '/api/v1/slack/contract-anniversary' },
  { method: 'POST', path: '/api/v1/slack/task-finished' }
];

const jiraRoutes = [
  { method: 'POST', path: '/api/v1/jira/create-bug' },
  { method: 'POST', path: '/api/v1/jira/create-story' },
  { method: 'POST', path: '/api/v1/jira/create-task' },
  { method: 'POST', path: '/api/v1/jira/add-comment' },
  { method: 'POST', path: '/api/v1/jira/move-issue' },
  { method: 'POST', path: '/api/v1/jira/close-issue' },
  { method: 'POST', path: '/api/v1/jira/reopen-issue' },
  { method: 'POST', path: '/api/v1/jira/change-priority' },
  { method: 'POST', path: '/api/v1/jira/assign-user' },
  { method: 'POST', path: '/api/v1/jira/create-epic' },
  { method: 'POST', path: '/api/v1/jira/link-epic' },
  { method: 'POST', path: '/api/v1/jira/update-description' },
  { method: 'POST', path: '/api/v1/jira/issues-by-status' },
  { method: 'POST', path: '/api/v1/jira/issues-by-assignee' },
  { method: 'POST', path: '/api/v1/jira/issues-by-epic' },
  { method: 'POST', path: '/api/v1/jira/add-watcher' },
  { method: 'POST', path: '/api/v1/jira/list-comments' },
  { method: 'POST', path: '/api/v1/jira/edit-comment' },
  { method: 'POST', path: '/api/v1/jira/delete-comment' },
  { method: 'POST', path: '/api/v1/jira/log-time' },
  { method: 'POST', path: '/api/v1/jira/report-sprint' },
  { method: 'POST', path: '/api/v1/jira/issues-by-label' },
  { method: 'POST', path: '/api/v1/jira/update-estimate' },
  { method: 'POST', path: '/api/v1/jira/list-sprints' },
  { method: 'GET',  path: '/api/v1/jira/list-projects' },
  { method: 'POST', path: '/api/v1/jira/create-subtask' },
  { method: 'POST', path: '/api/v1/jira/update-issue-type' },
  { method: 'POST', path: '/api/v1/jira/update-custom-field' },
  { method: 'POST', path: '/api/v1/jira/duplicate-issue' },
  { method: 'POST', path: '/api/v1/jira/close-sprint' },
  { method: 'POST', path: '/api/v1/jira/late-issues' },
  { method: 'POST', path: '/api/v1/jira/link-issues' },
  { method: 'POST', path: '/api/v1/jira/issues-by-release' },
  { method: 'POST', path: '/api/v1/jira/log-deploy' },
  { method: 'GET',  path: '/api/v1/jira/issue/:key' },
  { method: 'DELETE', path: '/api/v1/jira/delete-issue/:issueId' },
  { method: 'POST', path: '/api/v1/jira/update-due-date' },
  { method: 'POST', path: '/api/v1/jira/duplicate-sprint' },
  { method: 'POST', path: '/api/v1/jira/transfer-issue' },
  { method: 'POST', path: '/api/v1/jira/update-issue-sprint' },
  { method: 'POST', path: '/api/v1/jira/search-issues' },
  { method: 'POST', path: '/api/v1/jira/attach-file' },
  { method: 'POST', path: '/api/v1/jira/list-time-logs' },
  { method: 'POST', path: '/api/v1/jira/bulk-update-status' },
  { method: 'POST', path: '/api/v1/jira/update-reporter' },
  { method: 'POST', path: '/api/v1/jira/delay-report' },
  { method: 'POST', path: '/api/v1/jira/update-labels' },
  { method: 'POST', path: '/api/v1/jira/blocked-issues' },
  { method: 'POST', path: '/api/v1/jira/stats-by-type' },
  { method: 'POST', path: '/api/v1/jira/general-report' }
];

const googleRoutes = [
  { method: 'POST', path: '/api/v1/google/create-event' },
  { method: 'POST', path: '/api/v1/google/add-contact' },
  { method: 'POST', path: '/api/v1/google/send-gmail' },
  { method: 'POST', path: '/api/v1/google/create-gmail-draft' },
  { method: 'POST', path: '/api/v1/google/upload-drive' },
  { method: 'POST', path: '/api/v1/google/list-drive' },
  { method: 'POST', path: '/api/v1/google/share-drive-file' },
  { method: 'POST', path: '/api/v1/google/create-doc' },
  { method: 'POST', path: '/api/v1/google/update-doc' },
  { method: 'POST', path: '/api/v1/google/list-docs' },
  { method: 'POST', path: '/api/v1/google/create-sheet' },
  { method: 'POST', path: '/api/v1/google/add-row-sheets' },
  { method: 'POST', path: '/api/v1/google/update-row-sheets' },
  { method: 'POST', path: '/api/v1/google/read-sheet' },
  { method: 'GET',  path: '/api/v1/google/list-sheets' },
  { method: 'POST', path: '/api/v1/google/create-slides' },
  { method: 'POST', path: '/api/v1/google/add-slide' },
  { method: 'POST', path: '/api/v1/google/update-slide' },
  { method: 'POST', path: '/api/v1/google/share-slides' },
  { method: 'GET',  path: '/api/v1/google/list-slides' },
  { method: 'POST', path: '/api/v1/google/sync-calendar-sheet' },
  { method: 'POST', path: '/api/v1/google/create-task' },
  { method: 'POST', path: '/api/v1/google/update-task' },
  { method: 'GET',  path: '/api/v1/google/list-tasks' },
  { method: 'POST', path: '/api/v1/google/invite-to-event' },
  { method: 'POST', path: '/api/v1/google/cancel-event' },
  { method: 'POST', path: '/api/v1/google/export-sheet' },
  { method: 'POST', path: '/api/v1/google/convert-doc-pdf' },
  { method: 'POST', path: '/api/v1/google/auto-backup-drive' },
  { method: 'POST', path: '/api/v1/google/daily-agenda' },
  { method: 'POST', path: '/api/v1/google/send-push' },
  { method: 'POST', path: '/api/v1/google/short-link' },
  { method: 'POST', path: '/api/v1/google/activity-report' },
  { method: 'POST', path: '/api/v1/google/update-file-permission' },
  { method: 'POST', path: '/api/v1/google/register-lead-form' },
  { method: 'POST', path: '/api/v1/google/search-drive-file' },
  { method: 'POST', path: '/api/v1/google/attach-event-file' },
  { method: 'POST', path: '/api/v1/google/report-sheet' },
  { method: 'POST', path: '/api/v1/google/convert-sheet-pdf' },
  { method: 'POST', path: '/api/v1/google/unread-emails' },
  { method: 'POST', path: '/api/v1/google/mark-email-read' },
  { method: 'POST', path: '/api/v1/google/update-task-status' },
  { method: 'POST', path: '/api/v1/google/remove-event-participant' },
  { method: 'POST', path: '/api/v1/google/share-report' },
  { method: 'GET',  path: '/api/v1/google/list-folders' },
  { method: 'POST', path: '/api/v1/google/update-event-props' },
  { method: 'POST', path: '/api/v1/google/copy-drive-file' },
  { method: 'POST', path: '/api/v1/google/schedule-gmail' },
  { method: 'POST', path: '/api/v1/google/recurring-event' },
  { method: 'POST', path: '/api/v1/google/export-calendar' }
];

const hubspotRoutes = [
  { method: 'POST', path: '/api/v1/hubspot/create-contact' },
  { method: 'POST', path: '/api/v1/hubspot/update-contact' },
  { method: 'POST', path: '/api/v1/hubspot/find-contact' },
  { method: 'POST', path: '/api/v1/hubspot/create-deal' },
  { method: 'POST', path: '/api/v1/hubspot/update-deal' },
  { method: 'POST', path: '/api/v1/hubspot/move-deal-stage' },
  { method: 'POST', path: '/api/v1/hubspot/register-activity' },
  { method: 'POST', path: '/api/v1/hubspot/schedule-meeting' },
  { method: 'POST', path: '/api/v1/hubspot/add-note' },
  { method: 'POST', path: '/api/v1/hubspot/create-task' },
  { method: 'POST', path: '/api/v1/hubspot/update-task' },
  { method: 'POST', path: '/api/v1/hubspot/tasks-by-user' },
  { method: 'POST', path: '/api/v1/hubspot/create-ticket' },
  { method: 'POST', path: '/api/v1/hubspot/update-ticket' },
  { method: 'POST', path: '/api/v1/hubspot/client-feedback' },
  { method: 'POST', path: '/api/v1/hubspot/send-auto-email' },
  { method: 'POST', path: '/api/v1/hubspot/enroll-in-sequence' },
  { method: 'POST', path: '/api/v1/hubspot/cancel-sequence' },
  { method: 'POST', path: '/api/v1/hubspot/log-meeting' },
  { method: 'POST', path: '/api/v1/hubspot/update-custom-fields' },
  { method: 'POST', path: '/api/v1/hubspot/export-contacts' },
  { method: 'POST', path: '/api/v1/hubspot/export-deals' },
  { method: 'POST', path: '/api/v1/hubspot/export-activities' },
  { method: 'POST', path: '/api/v1/hubspot/import-contacts' },
  { method: 'POST', path: '/api/v1/hubspot/import-deals' },
  { method: 'POST', path: '/api/v1/hubspot/update-company' },
  { method: 'POST', path: '/api/v1/hubspot/create-company' },
  { method: 'POST', path: '/api/v1/hubspot/associate-company' },
  { method: 'POST', path: '/api/v1/hubspot/update-deal-owner' },
  { method: 'POST', path: '/api/v1/hubspot/log-communication' },
  { method: 'POST', path: '/api/v1/hubspot/timeline' },
  { method: 'POST', path: '/api/v1/hubspot/find-leads' },
  { method: 'POST', path: '/api/v1/hubspot/find-deals' },
  { method: 'POST', path: '/api/v1/hubspot/find-companies' },
  { method: 'POST', path: '/api/v1/hubspot/create-workflow' },
  { method: 'POST', path: '/api/v1/hubspot/toggle-workflow' },
  { method: 'POST', path: '/api/v1/hubspot/pipeline-report' },
  { method: 'POST', path: '/api/v1/hubspot/conversion-report' },
  { method: 'POST', path: '/api/v1/hubspot/update-lead-stage' },
  { method: 'POST', path: '/api/v1/hubspot/find-tasks' },
  { method: 'POST', path: '/api/v1/hubspot/update-contact-owner' },
  { method: 'POST', path: '/api/v1/hubspot/add-contact-note' },
  { method: 'POST', path: '/api/v1/hubspot/update-ticket-fields' },
  { method: 'GET',  path: '/api/v1/hubspot/list-workflows' },
  { method: 'GET',  path: '/api/v1/hubspot/list-sequences' },
  { method: 'POST', path: '/api/v1/hubspot/register-proposal' },
  { method: 'POST', path: '/api/v1/hubspot/close-deal' },
  { method: 'POST', path: '/api/v1/hubspot/send-lead-email' },
  { method: 'POST', path: '/api/v1/hubspot/tickets-report' },
  { method: 'POST', path: '/api/v1/hubspot/general-funnel-report' }
];

const apolloRoutes = [
  { method: 'POST', path: '/api/v1/apollo/enrich-lead' },
  { method: 'POST', path: '/api/v1/apollo/search-companies' },
  { method: 'POST', path: '/api/v1/apollo/search-leads' },
  { method: 'POST', path: '/api/v1/apollo/list-contacts' },
  { method: 'POST', path: '/api/v1/apollo/add-to-sequence' },
  { method: 'POST', path: '/api/v1/apollo/remove-from-sequence' },
  { method: 'POST', path: '/api/v1/apollo/update-lead-status' },
  { method: 'POST', path: '/api/v1/apollo/verify-email' },
  { method: 'POST', path: '/api/v1/apollo/send-personal-email' },
  { method: 'POST', path: '/api/v1/apollo/log-call' },
  { method: 'POST', path: '/api/v1/apollo/update-lead' },
  { method: 'POST', path: '/api/v1/apollo/create-company' },
  { method: 'POST', path: '/api/v1/apollo/associate-lead-company' },
  { method: 'POST', path: '/api/v1/apollo/icp-leads' },
  { method: 'POST', path: '/api/v1/apollo/find-opportunities' },
  { method: 'POST', path: '/api/v1/apollo/log-custom-activity' },
  { method: 'POST', path: '/api/v1/apollo/activity-report' },
  { method: 'POST', path: '/api/v1/apollo/update-lead-owner' },
  { method: 'POST', path: '/api/v1/apollo/add-lead-note' },
  { method: 'POST', path: '/api/v1/apollo/lead-engagement' },
  { method: 'POST', path: '/api/v1/apollo/generate-smart-list' },
  { method: 'POST', path: '/api/v1/apollo/import-leads' },
  { method: 'POST', path: '/api/v1/apollo/export-leads' },
  { method: 'POST', path: '/api/v1/apollo/conversion-report' },
  { method: 'POST', path: '/api/v1/apollo/create-opportunity' },
  { method: 'POST', path: '/api/v1/apollo/update-opportunity-status' },
  { method: 'POST', path: '/api/v1/apollo/opportunity-history' },
  { method: 'POST', path: '/api/v1/apollo/pipeline-report' },
  { method: 'POST', path: '/api/v1/apollo/contacts-by-role' },
  { method: 'POST', path: '/api/v1/apollo/update-company' },
  { method: 'POST', path: '/api/v1/apollo/add-lead-favorite' },
  { method: 'POST', path: '/api/v1/apollo/remove-lead-favorite' },
  { method: 'POST', path: '/api/v1/apollo/leads-by-source' },
  { method: 'POST', path: '/api/v1/apollo/update-contact' },
  { method: 'POST', path: '/api/v1/apollo/create-sequence' },
  { method: 'POST', path: '/api/v1/apollo/update-sequence' },
  { method: 'POST', path: '/api/v1/apollo/recently-engaged-leads' },
  { method: 'POST', path: '/api/v1/apollo/engagement-report' },
  { method: 'POST', path: '/api/v1/apollo/add-company-note' },
  { method: 'POST', path: '/api/v1/apollo/remove-lead-opportunity' },
  { method: 'POST', path: '/api/v1/apollo/update-custom-fields' },
  { method: 'POST', path: '/api/v1/apollo/opportunities-by-status' },
  { method: 'POST', path: '/api/v1/apollo/schedule-activity-reminder' },
  { method: 'POST', path: '/api/v1/apollo/lost-report' },
  { method: 'POST', path: '/api/v1/apollo/send-template-email' },
  { method: 'POST', path: '/api/v1/apollo/update-lead-score' },
  { method: 'POST', path: '/api/v1/apollo/leads-by-funnel' },
  { method: 'POST', path: '/api/v1/apollo/segmented-company-list' },
  { method: 'POST', path: '/api/v1/apollo/export-opportunities' },
  { method: 'POST', path: '/api/v1/apollo/general-report' }
];

registerRoutes(geminiRoutes);
registerRoutes(openaiRoutes);
registerRoutes(slackRoutes);
registerRoutes(jiraRoutes);
registerRoutes(googleRoutes);
registerRoutes(hubspotRoutes);
registerRoutes(apolloRoutes);

app.get('/', (req, res) => {
  res.json({ status: 'API server running' });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server listening on port ${PORT}`));
